
version: '3.8'

networks:
  proxy:
    driver: bridge
  
services:
  nginx:
    image: nginx 
    ports:
      - 8031:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - proxy
  php1:
    image: php:8.2-cli
    ports: 
      - 8032:80
    volumes:
    - ./php1:/usr/src/www
    command: php -S 0.0.0.0:80 -t usr/src/www
    networks:
      - proxy
  php2:
    image: php:8.2-cli
    ports: 
      - 8033:80
    volumes:
    - ./php2:/usr/src/www
    command:  php -S 0.0.0.0:80 -t usr/src/www
    networks:
      - proxy